name: CI

on:
  pull_request:

  push:
    branches:
      - nau/*.master

jobs:
  translations_is_missing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip # caching pip dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Check for missing translations on edx-platform
      run: make translations_is_missing
    - name: Install gettext package
      run: sudo apt-get install gettext
    - name: Check for missing translations on ecommerce
      run: make -C ecommerce translations_is_missing
